on:
  push:
    branches: [ master ]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
     - name: Postgres Container
       services:
       - name: postgres:latest
         alias: postgres
     - name: Install Dependency
       run: 
        - apt-get update -qy
        - apt-get install -y nodejs npm
        - npm install
     - name: Test
       run:
       - npm run build
       - npm run test:e2e
